name: Periodic Health Check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: call the health check endpoint of app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-1i6o.onrender.com/health
          max-attempts: 3
          retry-delay: 60s
      - name: send failure notification
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Pokedex health check failed
          message: https://full-stack-open-pokedex-1i6o.onrender.com/health
          colour: FF0000