name: Periodic Health Check

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: call the health check endpoint of app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-1i6o.onrender.com/health
          max-attempts: 3
          retry-delay: 60s
      - name: send failure notification
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "Pokedex health check failed"
          color: 0xFF0000
          description: https://full-stack-open-pokedex-1i6o.onrender.com/health
          username: "Periodic health check"