name: Periodic Health Check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: call the health check endpoint of app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-1i6o.onrender.com/health
          max-attempts: 1
          retry-delay: 5s
      - name: send failure notification
        if: ${{ failure() }}
        uses: rguillaume/discord-action-embed@v1.0.4
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: https://full-stack-open-pokedex-1i6o.onrender.com/health
          embed: '{ "color": FF0000, "title": "Pokedex health check failed" }'